### ISSUE TITLE
spacy.tokens.doc.Doc has the wrong size, try recompiling

### ISSUE THREAD

**Issue by veb** [honnibal/spaCy#109]
When I run:

`[0] % python -m spacy.en.download`

I get the following:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/usr/lib/python2.7/runpy.py", line 101, in _get_module_details
    loader = get_loader(mod_name)
  File "/usr/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/usr/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/usr/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "spacy/en/__init__.py", line 5, in <module>
    from ..language import Language
  File "spacy/language.py", line 9, in <module>
    from .tokenizer import Tokenizer
  File "spacy/vocab.pxd", line 27, in init spacy.tokenizer (spacy/tokenizer.cpp:8741)
    cdef class Vocab:
  File "spacy/serialize/packer.pxd", line 4, in init spacy.vocab (spacy/vocab.cpp:13788)
    cdef class Packer:
  File "spacy/tokens/doc.pxd", line 22, in init spacy.serialize.packer (spacy/serialize/packer.cpp:23390)
    cdef class Doc:
ValueError: spacy.tokens.doc.Doc has the wrong size, try recompiling
```

What's the best way to recompile?

**Comment by honnibal** [comment]
`pip install --upgrade spacy`?

**Comment by veb** [comment]
This is on my Ubuntu machine.

**Comment by veb** [comment]
```
(ssh) mike@veb ‹ master › : ~/spaCy
[137] % python -m spacy.en.download
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/usr/lib/python2.7/runpy.py", line 101, in _get_module_details
    loader = get_loader(mod_name)
  File "/usr/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/usr/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/usr/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "spacy/en/__init__.py", line 5, in <module>
    from ..language import Language
  File "spacy/language.py", line 9, in <module>
    from .tokenizer import Tokenizer
  File "spacy/vocab.pxd", line 27, in init spacy.tokenizer (spacy/tokenizer.cpp:8741)
    cdef class Vocab:
  File "spacy/serialize/packer.pxd", line 4, in init spacy.vocab (spacy/vocab.cpp:13788)
    cdef class Packer:
  File "spacy/tokens/doc.pxd", line 22, in init spacy.serialize.packer (spacy/serialize/packer.cpp:23390)
    cdef class Doc:
ValueError: spacy.tokens.doc.Doc has the wrong size, try recompiling
(.env)
```

**Comment by honnibal** [comment]
Oh, right.

```
python setup.py clean --all
python setup.py build_ext --inplace
```

I usually build the project in Python2, with Fabric. I do this with:

```
fab clean make test
```

**Comment by veb** [comment]
Heh. I tried:
```
[1] % python dev_setup.py clean
cleaning .c, .c++ and .so files matching sources
running clean
removing 'build/temp.linux-x86_64-2.7' (and everything under it)
removing 'build'
```

I don't know why I didn't think of setup.py, sorry.

*facepalm*

Giving it a try now...

**Comment by veb** [comment]
Perfect.

```
(ssh) mike@veb ‹ master › : ~/spaCy
[0] % python -m spacy.en.download
100% [......................................................................] 608118463 / 608118463%                                                                                                      (.env)
```

I then do py.test tests/

```
[0] % py.test tests/
Traceback (most recent call last):
  File "/home/mike/spaCy/.env/local/lib/python2.7/site-packages/_pytest/config.py", line 543, in importconftest
    mod = conftestpath.pyimport()
  File "/home/mike/spaCy/.env/local/lib/python2.7/site-packages/py/_path/local.py", line 650, in pyimport
    __import__(modname)
  File "/home/mike/spaCy/tests/conftest.py", line 2, in <module>
    from spacy.en import English, LOCAL_DATA_DIR
ImportError: No module named spacy.en
ERROR: could not load /home/mike/spaCy/tests/conftest.py
```

So I'm guessing it's the /tmp/ bug? So I rm -rf * in /tmp and try:
`[0] % python -m spacy.en.download` again

However error persists. I'm missing something jaw-droppingly obvious. I thought I had all the language packs installed globally from NLTK, etc

**Comment by veb** [comment]
Output of `import spacy.en; print(spacy.__file__)`
```
>>> import spacy.en; print(spacy.__file__)
spacy/__init__.pyc
>>>
```

**Comment by honnibal** [comment]
What's the output of `which py.test`? Can you do `pip install pytest`?

It sounds to me like the py.test that's being run isn't part of the same environment.

**Comment by veb** [comment]
```
[0] % which py.test
/home/mike/spaCy/.env/bin/py.test
```
pytest:

```
[0] % pip install pytest
Requirement already satisfied (use --upgrade to upgrade): pytest in ./.env/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): py>=1.4.29 in ./.env/lib/python2.7/site-packages (from pytest)
```

**Comment by veb** [comment]
Wait. `/home/mike/spaCy/.env/bin/py.test` isn't in the right place is it?

**Comment by honnibal** [comment]
that looks right to me

**Comment by veb** [comment]
```
(ssh) mike@veb ‹ master ● › : ~/spaCy/tests
[2] % python conftest.py
Traceback (most recent call last):
  File "conftest.py", line 2, in <module>
    from spacy.en import English, LOCAL_DATA_DIR
ImportError: No module named spacy.en
(.env)
```

**Comment by veb** [comment]
Sigh.

The very line I decided to skip thinking it was ALREADY in my path, was the problem. I apologise about that.

```
(ssh) mike@veb ‹ master › : ~/spaCy
[4] % export PYTHONPATH=`pwd`
(.env)
(ssh) mike@veb ‹ master › : ~/spaCy
[0] % py.test tests/
========================================================================================== test session starts ===========================================================================================
platform linux2 -- Python 2.7.6, pytest-2.8.0, py-1.4.30, pluggy-0.3.1
rootdir: /home/mike/spaCy, inifile:
collected 202 items

tests/test_matcher.py [1]    16007 killed     py.test tests/
(.env)
(ssh) mike@veb ‹ master › : ~/spaCy
[137] %
```

**Comment by honnibal** [comment]
Great --- let me know if you have any other problems. Also, first impressions on the docs are always very welcome :)

**Comment by veb** [comment]
Not over yet!

No examples work.

Notice my last post: `tests/test_matcher.py [1]    16007 killed     py.test tests/`

**Comment by veb** [comment]
If I try any examples, they are instantly killed.

**Comment by honnibal** [comment]
How much memory do you have? You need at least 2gb.

**Comment by veb** [comment]
Nope. English is missing somehow.

**Comment by honnibal** [comment]
Hmm.

If you didn't have your PYTHONPATH set before, maybe the install command used some other spacy.en.download? 

It's also possible you got your installation into some sort of strange state before.

**Comment by veb** [comment]
Yep, doing that already, sec.

**Comment by veb** [comment]
I think you've answered the question, and we managed to figure out how to recompile etc. Which will be helpful for others in the future.

I'll close this issue now. I'll redo all this again in another env, and if the English/tests thing persist, I will add a new issue. Is that cool?
