### ISSUE TITLE
Upgrade/Installation Issue 0.97 (Centos5.8)

### ISSUE THREAD

**Issue by vivekx** [honnibal/spaCy#155]
Hi,

I have upgraded to spacy 0.97 and re-downloaded data. On running it gives following error:

  File "spacy/vocab.pyx", line 134, in spacy.vocab.Vocab.get (spacy/vocab.cpp:5645)
spacy.vocab.LookupError: Error fetching a Lexeme from the Vocab. When looking up a string, the lexeme returned had an orth ID that did not match the query string. This means that the cached lexeme structs are mismatched to the string encoding table. The mismatched:
Query string: 	
Orth cached: 	
ID of orth: 1958

Checked another similar issue but that mentioned it was resolved in 0.95. 
I did a fresh install on a new machine and that works perfectly. However, on current machine I'm getting the error despite uninstalling and reinstalling via pip as well (including deletion of folder from site-packages). 

One difference I noticed in the two machines was that in the fresh machine (running centos 7), the directory was /usr/lib64/python2.7 whereas in the old one (running centos5.8) it was /usr/lib/python2.7.

Please advise resolution / work-around. Thanks.

**Comment by honnibal** [comment]
Hey,

Did you redownload the data after upgrading?

    python -m spacy.en.download --force all

**Comment by vivekx** [comment]
Yes, I did that. The current data tgz being downloaded is:
en_data_all-0.9.6.tgz

**Comment by henningpeters** [comment]
Can you please run the following command on your system:

```find `python -c 'import os; import spacy.en; print(os.path.dirname(spacy.en.__file__))'````

This should print the content of spacy's data directory.

**Comment by vivekx** [comment]
Hi,

Please find below.

find `python2.7 -c 'import os; import spacy.en;
print(os.path.dirname(spacy.en.__file__))'`
/usr/lib/python2.7/site-packages/spacy/en
/usr/lib/python2.7/site-packages/spacy/en/regexes.pyc
/usr/lib/python2.7/site-packages/spacy/en/data
/usr/lib/python2.7/site-packages/spacy/en/data/vocab
/usr/lib/python2.7/site-packages/spacy/en/data/vocab/lemma_rules.json
/usr/lib/python2.7/site-packages/spacy/en/data/vocab/tag_map.json
/usr/lib/python2.7/site-packages/spacy/en/data/vocab/vec.bin
/usr/lib/python2.7/site-packages/spacy/en/data/vocab/oov_prob
/usr/lib/python2.7/site-packages/spacy/en/data/vocab/strings.json
/usr/lib/python2.7/site-packages/spacy/en/data/vocab/lexemes.bin
/usr/lib/python2.7/site-packages/spacy/en/data/vocab/gazetteer.json
/usr/lib/python2.7/site-packages/spacy/en/data/vocab/serializer.json
/usr/lib/python2.7/site-packages/spacy/en/data/pos
/usr/lib/python2.7/site-packages/spacy/en/data/pos/model
/usr/lib/python2.7/site-packages/spacy/en/data/wordnet
/usr/lib/python2.7/site-packages/spacy/en/data/wordnet/sentidx.vrb
/usr/lib/python2.7/site-packages/spacy/en/data/wordnet/index.adv
/usr/lib/python2.7/site-packages/spacy/en/data/wordnet/adv.exc
/usr/lib/python2.7/site-packages/spacy/en/data/wordnet/verb.Framestext
/usr/lib/python2.7/site-packages/spacy/en/data/wordnet/frames.vrb
/usr/lib/python2.7/site-packages/spacy/en/data/wordnet/adj.exc
/usr/lib/python2.7/site-packages/spacy/en/data/wordnet/index.noun
/usr/lib/python2.7/site-packages/spacy/en/data/wordnet/index.verb
/usr/lib/python2.7/site-packages/spacy/en/data/wordnet/verb.exc
/usr/lib/python2.7/site-packages/spacy/en/data/wordnet/noun.exc
/usr/lib/python2.7/site-packages/spacy/en/data/wordnet/sents.vrb
/usr/lib/python2.7/site-packages/spacy/en/data/wordnet/index.adj
/usr/lib/python2.7/site-packages/spacy/en/data/deps
/usr/lib/python2.7/site-packages/spacy/en/data/deps/model
/usr/lib/python2.7/site-packages/spacy/en/data/ner
/usr/lib/python2.7/site-packages/spacy/en/data/ner/config.json
/usr/lib/python2.7/site-packages/spacy/en/data/ner/model
/usr/lib/python2.7/site-packages/spacy/en/data/tokenizer
/usr/lib/python2.7/site-packages/spacy/en/data/tokenizer/morphs.json
/usr/lib/python2.7/site-packages/spacy/en/data/tokenizer/infix.txt
/usr/lib/python2.7/site-packages/spacy/en/data/tokenizer/prefix.txt
/usr/lib/python2.7/site-packages/spacy/en/data/tokenizer/specials.json
/usr/lib/python2.7/site-packages/spacy/en/data/tokenizer/suffix.txt
/usr/lib/python2.7/site-packages/spacy/en/uget.py
/usr/lib/python2.7/site-packages/spacy/en/download.py
/usr/lib/python2.7/site-packages/spacy/en/download.pyc
/usr/lib/python2.7/site-packages/spacy/en/__init__.py
/usr/lib/python2.7/site-packages/spacy/en/regexes.py
/usr/lib/python2.7/site-packages/spacy/en/en_data_all-0.9.6.tgz
/usr/lib/python2.7/site-packages/spacy/en/uget.pyc
/usr/lib/python2.7/site-packages/spacy/en/__init__.pyc


Regards,
Vivek Arya

**Comment by gibrown** [comment]
Just another data point, I am seeing the same error with 0.97. 

If I install a previous version (0.96?), Is it possible to download the previous data also? I had previously had 0.94 installed, and downloading the data seemed to get the newer data files and resulted in errors.

Note we're installed in a slightly non-normal location, but everything else works well.
```
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/__init__.pyc
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/data
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/data/wordnet
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/data/wordnet/verb.Framestext
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/data/wordnet/adj.exc
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/data/wordnet/index.adv
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/data/wordnet/index.adj
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/data/wordnet/sents.vrb
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/data/wordnet/sentidx.vrb
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/data/wordnet/verb.exc
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/data/wordnet/adv.exc
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/data/wordnet/index.verb
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/data/wordnet/noun.exc
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/data/wordnet/frames.vrb
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/data/wordnet/index.noun
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/data/vocab
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/data/vocab/oov_prob
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/data/vocab/lexemes.bin
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/data/vocab/tag_map.json
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/data/vocab/vec.bin
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/data/vocab/gazetteer.json
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/data/vocab/serializer.json
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/data/vocab/lemma_rules.json
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/data/vocab/strings.json
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/data/tokenizer
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/data/tokenizer/morphs.json
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/data/tokenizer/suffix.txt
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/data/tokenizer/prefix.txt
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/data/tokenizer/infix.txt
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/data/tokenizer/specials.json
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/data/ner
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/data/ner/config.json
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/data/ner/model
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/data/pos
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/data/pos/model
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/data/deps
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/data/deps/config.json
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/data/deps/model
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/regexes.pyc
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/download.pyc
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/regexes.py
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/download.py
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/__init__.py
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/en_data_all-0.9.6.tgz
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/uget.pyc
/home/slack-summary/local/lib/python2.7/site-packages/spacy/en/uget.py
```

**Comment by honnibal** [comment]
Each version should download the correct data --- it's specified in
download.py, and the older models are still hosted.

**Comment by henningpeters** [comment]
Everything spaCy relies on should be contained in the spacy package directory where it was installed (e.g., via pip), this includes the downloaded and extracted data archive. Hence, the install location should not matter.

Also, as @honnibal said each spaCy version has the url hardcoded from which it downloads the data archive and deletes old extracted files before extracting the new archive. Hence, an upgrade should not be any different than a fresh install.

@gibrown can you confirm that you don't get the issue after doing a fresh install? I want to check whether the problems is related to upgrades.

Could you also please run and paste following snippet that gathers information about your python environment:

https://gist.github.com/henningpeters/22d2aa6979916572e649

**Comment by gibrown** [comment]
I think the root problem may be that we are running debian oldstable.

Had to comment out a bunch of stuff that wasn't working in that script (most of the pip stuff, and some , and removed some server info.

```
--- python ---
build default
compiler GCC 4.7.2
implementation CPython
version 2.7.3
branch
revision
has_64bits True
path ['/home/slack-summary', '/home/slack-summary/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg', '/home/slack-summary/lib/python2.7/site-packages/pip-1.1-py2.7.egg', '/home/slack-summary/lib/python2.7', '/home/slack-summary/lib/python2.7/plat-linux2', '/home/slack-summary/lib/python2.7/lib-tk', '/home/slack-summary/lib/python2.7/lib-old', '/home/slack-summary/lib/python2.7/lib-dynload', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-linux2', '/usr/lib/python2.7/lib-tk', '/home/slack-summary/local/lib/python2.7/site-packages', '/home/slack-summary/lib/python2.7/site-packages']
env: PYTHONPATH None

--- system ---
system Linux
version 3.10-0.bpo.2-amd64
machine #1 SMP Debian 3.10.5-1~bpo70+1 (2013-08-11)
processor x86_64
linux_distribution ('debian', '7.9', '')
libc_ver ('glibc', '2.7')

--- pip ---
path ['/home/slack-summary/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip']

--- compiler ---
env: CC None
env: CXX None
$ gcc gcc (Debian 4.7.2-5) 4.7.2 Copyright (C) 2012 Free Software Foundation, Inc. This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$ g++ g++ (Debian 4.7.2-5) 4.7.2 Copyright (C) 2012 Free Software Foundation, Inc. This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Here is the stuff i commented out. (I didn't check all of the pip stuff, but most of those vars did not exist).

```
    #print("version", pip.__version__)
    #print("locations.bin_py", pip.locations.bin_py)
    #print("locations.bin_user", pip.locations.bin_user)
    #print("locations.site_config_files", pip.locations.site_config_files)
    #print("locations.src_prefix", pip.locations.src_prefix)
    #print("locations.user_dir", pip.locations.user_dir)
    #print("locations.user_site", pip.locations.user_site)
    #print("locations.running_under_virtualenv", pip.locations.running_under_virtualenv())
    #print("locations.virtualenv_no_global", pip.locations.virtualenv_no_global())
    #print("locations.installed_distributions", pip.get_installed_distributions())
#print("$ clang", call("clang", "--version"))
#print("$ cython", call("cython", "--version"))
```

I then upgraded pip to the latest, uninstalled spacy, deleted the data files, reinstalled everything (0.98 now), and am still seeing the same error.

So still kinda stuck unfortunately. :(

Reran your script with the new pip installed, and here is the output:

```
--- python ---
build default
compiler GCC 4.7.2
implementation CPython
version 2.7.3
branch
revision
has_64bits True
path ['/home/slack-summary', '/home/slack-summary/lib/python2.7', '/home/slack-summary/lib/python2.7/plat-linux2', '/home/slack-summary/lib/python2.7/lib-tk', '/home/slack-summary/lib/python2.7/lib-old', '/home/slack-summary/lib/python2.7/lib-dynload', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-linux2', '/usr/lib/python2.7/lib-tk', '/home/slack-summary/local/lib/python2.7/site-packages', '/home/slack-summary/lib/python2.7/site-packages']
env: PYTHONPATH None

--- system ---
system Linux
version 3.10-0.bpo.2-amd64
machine #1 SMP Debian 3.10.5-1~bpo70+1 (2013-08-11)
processor x86_64
linux_distribution ('debian', '7.9', '')
libc_ver ('glibc', '2.7')

--- pip ---
version 7.1.2
path ['/home/slack-summary/local/lib/python2.7/site-packages/pip']
locations.bin_py /home/slack-summary/bin
locations.bin_user /home/slack-summary/.local/lib/python2.7/site-packages/bin
locations.site_config_files ['/etc/xdg/pip/pip.conf', '/etc/pip.conf']
locations.src_prefix /home/slack-summary/src
locations.user_dir /home/slack-summary
locations.user_site /home/slack-summary/.local/lib/python2.7/site-packages
locations.running_under_virtualenv True
locations.virtualenv_no_global True
locations.installed_distributions [smart-open 1.3.0 (/home/slack-summary/lib/python2.7/site-packages), Pygments 2.0.2 (/home/slack-summary/lib/python2.7/site-packages), pexpect 4.0.1 (/home/slack-summary/lib/python2.7/site-packages), ipykernel 4.1.1 (/home/slack-summary/lib/python2.7/site-packages), wget 3.2 (/home/slack-summary/lib/python2.7/site-packages), idna 2.0 (/home/slack-summary/lib/python2.7/site-packages), backports-abc 0.4 (/home/slack-summary/lib/python2.7/site-packages), jupyter-core 4.0.6 (/home/slack-summary/lib/python2.7/site-packages), pip 7.1.2 (/home/slack-summary/lib/python2.7/site-packages), plac 0.9.1 (/home/slack-summary/lib/python2.7/site-packages), bz2file 0.98 (/home/slack-summary/lib/python2.7/site-packages), scikit-learn 0.16.1 (/home/slack-summary/lib/python2.7/site-packages), clusterpoint-api 0.3.0 (/home/slack-summary/lib/python2.7/site-packages), preshed 0.43 (/home/slack-summary/lib/python2.7/site-packages), ipaddress 1.0.14 (/home/slack-summary/lib/python2.7/site-packages), tornado 4.3b1 (/home/slack-summary/lib/python2.7/site-packages), backports.ssl-match-hostname 3.4.0.2 (/home/slack-summary/lib/python2.7/site-packages), distribute 0.7.3 (/home/slack-summary/lib/python2.7/site-packages), jupyter 1.0.0 (/home/slack-summary/lib/python2.7/site-packages), pyOpenSSL 0.15.1 (/home/slack-summary/lib/python2.7/site-packages), funcsigs 0.4 (/home/slack-summary/lib/python2.7/site-packages), singledispatch 3.4.0.3 (/home/slack-summary/lib/python2.7/site-packages), nltk 3.0.3 (/home/slack-summary/lib/python2.7/site-packages), decorator 3.4.2 (/home/slack-summary/lib/python2.7/site-packages), enum34 1.0.4 (/home/slack-summary/lib/python2.7/site-packages), nbformat 4.0.1 (/home/slack-summary/lib/python2.7/site-packages), ujson 1.33 (/home/slack-summary/lib/python2.7/site-packages), ipython 4.0.0 (/home/slack-summary/lib/python2.7/site-packages), requests 2.8.1 (/home/slack-summary/lib/python2.7/site-packages), boto 2.38.0 (/home/slack-summary/lib/python2.7/site-packages), ptyprocess 0.5 (/home/slack-summary/lib/python2.7/site-packages), MarkupSafe 0.23 (/home/slack-summary/lib/python2.7/site-packages), spacy 0.98 (/home/slack-summary/lib/python2.7/site-packages), pbr 1.8.1 (/home/slack-summary/lib/python2.7/site-packages), cymem 1.30 (/home/slack-summary/lib/python2.7/site-packages), murmurhash 0.24 (/home/slack-summary/lib/python2.7/site-packages), pycps 0.3.0 (/home/slack-summary/lib/python2.7/site-packages), notebook 4.0.6 (/home/slack-summary/lib/python2.7/site-packages), nbconvert 4.0.0 (/home/slack-summary/lib/python2.7/site-packages), jupyter-console 4.0.3 (/home/slack-summary/lib/python2.7/site-packages), pyasn1 0.1.8 (/home/slack-summary/lib/python2.7/site-packages), httpretty 0.8.6 (/home/slack-summary/lib/python2.7/site-packages), pickleshare 0.5 (/home/slack-summary/lib/python2.7/site-packages), cloudpickle 0.1.1 (/home/slack-summary/lib/python2.7/site-packages), pyzmq 14.7.0 (/home/slack-summary/lib/python2.7/site-packages), slacker 0.6.2 (/home/slack-summary/lib/python2.7/site-packages), gensim 0.12.2 (/home/slack-summary/lib/python2.7/site-packages), itsdangerous 0.24 (/home/slack-summary/lib/python2.7/site-packages), pycparser 2.14 (/home/slack-summary/lib/python2.7/site-packages), ipywidgets 4.1.0 (/home/slack-summary/lib/python2.7/site-packages), Werkzeug 0.10.4 (/home/slack-summary/lib/python2.7/site-packages), jsonschema 2.5.1 (/home/slack-summary/lib/python2.7/site-packages), text-unidecode 1.0 (/home/slack-summary/lib/python2.7/site-packages), networkx 1.9.1 (/home/slack-summary/lib/python2.7/site-packages), traitlets 4.0.0 (/home/slack-summary/lib/python2.7/site-packages), ndg-httpsclient 0.4.0 (/home/slack-summary/lib/python2.7/site-packages), six 1.10.0 (/home/slack-summary/lib/python2.7/site-packages), certifi 2015.9.6.2 (/home/slack-summary/lib/python2.7/site-packages), cffi 1.2.1 (/home/slack-summary/lib/python2.7/site-packages), thinc 3.4.1 (/home/slack-summary/lib/python2.7/site-packages), Jinja2 2.7.3 (/home/slack-summary/lib/python2.7/site-packages), jupyter-client 4.1.1 (/home/slack-summary/lib/python2.7/site-packages), setuptools 18.4 (/home/slack-summary/lib/python2.7/site-packages), path.py 8.1.2 (/home/slack-summary/lib/python2.7/site-packages), scipy 0.14.0 (/home/slack-summary/lib/python2.7/site-packages), numpy 1.10.1 (/home/slack-summary/lib/python2.7/site-packages), qtconsole 4.1.0 (/home/slack-summary/lib/python2.7/site-packages), Flask 0.10.1 (/home/slack-summary/lib/python2.7/site-packages), simplegeneric 0.8.1 (/home/slack-summary/lib/python2.7/site-packages), mistune 0.7.1 (/home/slack-summary/lib/python2.7/site-packages), cryptography 1.0.1 (/home/slack-summary/lib/python2.7/site-packages), mock 1.3.0 (/home/slack-summary/lib/python2.7/site-packages), ipython-genutils 0.1.0 (/home/slack-summary/lib/python2.7/site-packages)]

--- compiler ---
env: CC None
env: CXX None
$ gcc gcc (Debian 4.7.2-5) 4.7.2 Copyright (C) 2012 Free Software Foundation, Inc. This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$ g++ g++ (Debian 4.7.2-5) 4.7.2 Copyright (C) 2012 Free Software Foundation, Inc. This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Error is still:

```
Traceback (most recent call last):
  File "test_service_components.py", line 6, in <module>
    import main
  File "/home/slack-summary/src/main.py", line 14, in <module>
    summ = lsa.LsaSummarizer()
  File "/home/slack-summary/src/lsa.py", line 35, in __init__
    self.nlp = spacy.en.English(entity=False, matcher=False)
  File "/home/slack-summary/local/lib/python2.7/site-packages/spacy/language.py", line 195, in __init__
    tokenizer = self.default_tokenizer(vocab, data_dir=path.join(data_dir, 'tokenizer'))
  File "/home/slack-summary/local/lib/python2.7/site-packages/spacy/language.py", line 153, in default_tokenizer
    return Tokenizer.from_dir(vocab, data_dir)
  File "spacy/tokenizer.pyx", line 49, in spacy.tokenizer.Tokenizer.from_dir (spacy/tokenizer.cpp:3573)
  File "spacy/tokenizer.pyx", line 31, in spacy.tokenizer.Tokenizer.__init__ (spacy/tokenizer.cpp:3067)
  File "spacy/tokenizer.pyx", line 271, in spacy.tokenizer.Tokenizer._load_special_tokenization (spacy/tokenizer.cpp:6655)
  File "spacy/vocab.pyx", line 223, in spacy.vocab.Vocab.make_fused_token (spacy/vocab.cpp:7063)
  File "spacy/vocab.pyx", line 137, in spacy.vocab.Vocab.get (spacy/vocab.cpp:5760)
spacy.vocab.LookupError: Error fetching a Lexeme from the Vocab. When looking up a string, the lexeme returned had an orth ID that did not match the query string. This means that the cached lexeme structs are mismatched to the string encoding table. The mismatched:
Query string:
Orth cached:
ID of orth: 1958
```

**Comment by honnibal** [comment]
@gibrown Hmm. Setting up an EC2 image now.

I don't really get what on the OS could be causing this. My hunch is still that there's some sort of weird Python path/environment/installation thing, and that there's some other spaCy data being used.

I'll let you know once the instance is running.

**Comment by honnibal** [comment]
Okay replicated the problem as follows:

AMI: debian-wheezy-amd64-pvm-2015-01-28-ebs

```bash

$ sudo apt-get update
$ sudo apt-get install build-essential python-dev python-virtualenv
$ virtualenv env
$ source env/bin/activate
$ pip install --upgrade pip
$ pip install --upgrade setuptools
$ pip install spacy
$ python -m spacy.en.download --force all
$ python -c "import spacy.en; nlp = spacy.en.English(); doc = nlp(u'This is a test. This is a second sentence'); print(len(list(doc.sents)))"
```

Weird. Will let you know what I come up with.

**Comment by honnibal** [comment]
Works on Ubuntu Trusty Python 2.7.9 GCC 4.8.4

Will continue narrowing it down.

**Comment by gibrown** [comment]
Cool, glad you were able to replicate at least and I am not entirely crazy.

**Comment by honnibal** [comment]
Think I've got this figured out.

The bug is specific to wide-unicode Python 2 builds, and comes from a bad type-cast from a Python object to char*, while hashing the string.

Fix should be completed shortly. Really need to get a full build matrix going.

**Comment by honnibal** [comment]
This was an interesting one. An iteration function in the hash table, preshed, was depending on an uninitialised value. This happened to work on all the platforms being tested --- but happened to break here, possibly due to an interaction between this bug, Python 2, and a wide unicode build.

I've got this fixed now, but I'm reviewing some of the associated code before releasing the patch.

**Comment by gibrown** [comment]
unicode is fun sometimes. :)

Thanks for fixing this so fast. I had pretty much expected that this wasn't going to be fixable in the short time period we are on for this phase of this project. Really exciting. Much appreciated.

**Comment by gibrown** [comment]
@honnibal just wanted to say thanks again, and that this fix is working for us.
