### ISSUE TITLE
Runtime error (max recursion depth exceeded) when printing tokens

### ISSUE THREAD

**Issue by dschallis** [honnibal/spaCy#16]
Under python 3.4, spaCy 0.33, printing tokens from the spaCy example:

    import spacy.en
    nlp = spacy.en.English()
    tokens = nlp("‘Give it back,’ he pleaded abjectly, ‘it’s mine.’", tag=True, parse=False)                          
    print(tokens) 

Fails with:

    Traceback (most recent call last):
      File "t.py", line 7, in <module>
        print(tokens)
      File "spacy/tokens.pyx", line 140, in spacy.tokens.Tokens.__str__ (spacy/tokens.cpp:4222)
      File "spacy/tokens.pyx", line 140, in spacy.tokens.Tokens.__str__ (spacy/tokens.cpp:4222)
      File "spacy/tokens.pyx", line 140, in spacy.tokens.Tokens.__str__ (spacy/tokens.cpp:4222)
      File "spacy/tokens.pyx", line 140, in spacy.tokens.Tokens.__str__ (spacy/tokens.cpp:4222)
    ... above repeats until ...
    RuntimeError: maximum recursion depth exceeded while calling a Python object

**Comment by honnibal** [comment]
Thanks for the report, fixed.
