### ISSUE TITLE
Problem downloading spacy models

### ISSUE THREAD

**Issue by tokestermw** [honnibal/spaCy#162]
I am currently using the following versions of the scientific libraries:

numpy==1.10.1
scipy==0.16.1
spacy==0.97

I am using Python 2.7.10 inside a virtualenv and gives out this error.

```
$ python -m spacy.en.download
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 101, in _get_module_details
    loader = get_loader(mod_name)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "/Users/apewu/venv/lib/python2.7/site-packages/spacy/en/__init__.py", line 5, in <module>
    from ..language import Language
  File "/Users/apewu/venv/lib/python2.7/site-packages/spacy/language.py", line 10, in <module>
    from .tokenizer import Tokenizer
  File ".env/lib/python3.4/site-packages/cymem/cymem.pxd", line 1, in init spacy.tokenizer (spacy/tokenizer.cpp:9218)
ValueError: cymem.cymem.Pool has the wrong size, try recompiling
```

Last line of the log looks like it's using python3.4? 

Also, I am using Mac OS X 10.10.1. Thanks.

**Comment by honnibal** [comment]
This is my bad — I updated the `cymem` package last night and haven't pushed a new version of spaCy yet. It'll be fixed within a few hours.

**Comment by honnibal** [comment]
Pushed v0.98. Try now.
