### ISSUE TITLE
If installed from PyPI, cannot import

### ISSUE THREAD

**Issue by tomtung** [honnibal/spaCy#163]
Environment: OS X 10.10.5, Python 2.7.10

To reproduce:

```
# in ~/tmp
$ mkdir tmptmp; cd tmptmp

# in ~/tmp/tmptmp
$ virtualenv venv
New python executable in venv/bin/python2.7
Also creating executable in venv/bin/python
Installing setuptools, pip, wheel...done.

# in ~/tmp/tmptmp
$ source venv/bin/activate

(venv)
# in ~/tmp/tmptmp
$ pip install --upgrade spacy
Collecting spacy
Collecting cymem>=1.11 (from spacy)
Collecting murmurhash (from spacy)
Collecting text-unidecode (from spacy)
  Using cached text_unidecode-1.0-py2.py3-none-any.whl
Collecting preshed>=0.42 (from spacy)
Collecting six (from spacy)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting numpy (from spacy)
  Using cached numpy-1.10.1-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting cloudpickle (from spacy)
  Using cached cloudpickle-0.1.1-py2.py3-none-any.whl
Collecting thinc==3.3 (from spacy)
Collecting plac (from spacy)
Collecting ujson (from spacy)
Installing collected packages: cymem, murmurhash, text-unidecode, preshed, six, numpy, cloudpickle, thinc, plac, ujson, spacy
Successfully installed cloudpickle-0.1.1 cymem-1.30 murmurhash-0.24 numpy-1.10.1 plac-0.9.1 preshed-0.43 six-1.10.0 spacy-0.97 text-unidecode-1.0 thinc-3.3 ujson-1.33

# in ~/tmp/tmptmp
$ python
Python 2.7.10 (default, Jun  1 2015, 09:44:56)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from spacy.syntax.ner import BiluoPushDown
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "spacy/syntax/ner.pyx", line 1, in init spacy.syntax.ner (spacy/syntax/ner.cpp:8857)
  File ".env/lib/python3.4/site-packages/cymem/cymem.pxd", line 1, in init spacy.syntax.transition_system (spacy/syntax/transition_system.cpp:5709)
ValueError: cymem.cymem.Pool has the wrong size, try recompiling
>>> from spacy.syntax.ner import BiluoPushDown
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name BiluoPushDown
>>> from spacy.syntax.ner import BiluoPushDown
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name BiluoPushDown
>>>
```

And the library basically cannot function.

But the following works (after creating the venv in the same way):

```
(venv)
# in ~/tmp/tmptmp
$ git clone https://github.com/honnibal/spaCy.git

(venv)
# in ~/tmp/tmptmp
$ cd spaCy

(venv)
# in ~/tmp/tmptmp/spaCy on git:master
$ pip install -r requirements.txt
...
Installing collected packages: cython, cymem, pathlib, murmurhash, preshed, thinc, text-unidecode, numpy, plac, six, ujson, cloudpickle
Successfully installed cloudpickle-0.1.1 cymem-1.30 cython-0.23.4 murmurhash-0.24 numpy-1.10.1 pathlib-1.0.1 plac-0.9.1 preshed-0.43 six-1.10.0 text-unidecode-1.0 thinc-3.4.1 ujson-1.33

(venv)
# in ~/tmp/tmptmp/spaCy on git:master
$ python setup.py build_ext
...

(venv)
# in ~/tmp/tmptmp/spaCy on git:master
$ python setup.py sdist
...

(venv)
# in ~/tmp/tmptmp/spaCy on git:master
$ cd dist

# in ~/tmp/tmptmp/spaCy/dist on git:master
$ pip install spacy-0.98.tar.gz
Processing ./spacy-0.98.tar.gz
Requirement already satisfied (use --upgrade to upgrade): numpy in /Users/yubing/tmp/tmptmp/venv/lib/python2.7/site-packages (from spacy==0.98)
Requirement already satisfied (use --upgrade to upgrade): murmurhash in /Users/yubing/tmp/tmptmp/venv/lib/python2.7/site-packages (from spacy==0.98)
Requirement already satisfied (use --upgrade to upgrade): cymem>=1.30 in /Users/yubing/tmp/tmptmp/venv/lib/python2.7/site-packages (from spacy==0.98)
Requirement already satisfied (use --upgrade to upgrade): preshed>=0.43 in /Users/yubing/tmp/tmptmp/venv/lib/python2.7/site-packages (from spacy==0.98)
Requirement already satisfied (use --upgrade to upgrade): thinc>=3.4.1 in /Users/yubing/tmp/tmptmp/venv/lib/python2.7/site-packages (from spacy==0.98)
Requirement already satisfied (use --upgrade to upgrade): text-unidecode in /Users/yubing/tmp/tmptmp/venv/lib/python2.7/site-packages (from spacy==0.98)
Requirement already satisfied (use --upgrade to upgrade): plac in /Users/yubing/tmp/tmptmp/venv/lib/python2.7/site-packages (from spacy==0.98)
Requirement already satisfied (use --upgrade to upgrade): six in /Users/yubing/tmp/tmptmp/venv/lib/python2.7/site-packages (from spacy==0.98)
Requirement already satisfied (use --upgrade to upgrade): ujson in /Users/yubing/tmp/tmptmp/venv/lib/python2.7/site-packages (from spacy==0.98)
Requirement already satisfied (use --upgrade to upgrade): cloudpickle in /Users/yubing/tmp/tmptmp/venv/lib/python2.7/site-packages (from spacy==0.98)
Building wheels for collected packages: spacy
  Running setup.py bdist_wheel for spacy
  Stored in directory: /Users/yubing/Library/Caches/pip/wheels/ba/12/c4/35275506b939f9fa8aad91f9977b60904e199a09473c436066
Successfully built spacy
Installing collected packages: spacy
Successfully installed spacy-0.98

(venv)
# in ~/tmp/tmptmp/spaCy/dist on git:master
$ python
Python 2.7.10 (default, Jun  1 2015, 09:44:56)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from spacy.syntax.ner import BiluoPushDown
>>>
```

And the library functions well.

Maybe it's better to include Cython compilation as part of the standard installation procedure (at the cost of requiring Cython during installation from PyPI)?

**Comment by honnibal** [comment]
I've broken the build --- I'm uploading to PyPi in the next few minutes.

Sorry about this.

**Comment by tomtung** [comment]
No worries; good to know :)

**Comment by tomtung** [comment]
Works now, thanks!
