### ISSUE TITLE
Spacy assumes data is already downloaded.

### ISSUE THREAD

**Issue by jamorton** [honnibal/spaCy#183]
Using spacy on Python 3.5 after installing with pip, I get this error:

```
>>> import spacy.en
>>> nlp = spacy.en.English()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "env/lib/python3.5/site-packages/spacy/language.py", line 193, in __init__
    vocab = self.default_vocab(data_dir)
  File "env/lib/python3.5/site-packages/spacy/language.py", line 148, in default_vocab
    get_lex_attr=get_lex_attr)
  File "spacy/vocab.pyx", line 56, in spacy.vocab.Vocab.from_dir (spacy/vocab.cpp:3461)
FileNotFoundError: [Errno 2] No such file or directory: 'env/lib/python3.5/site-packages/spacy/en/data/vocab/tag_map.json'
```

I assumed this was because I needed to download the English data:

```
(env) ➜ python -m spacy.en.download all
data already installed at /Users/jamorton/dev/bucket/env/lib/python3.5/site-packages/spacy/en, overwrite with --force
```

But spacy thinks it's already there.

I had to run download with --force to get it to work.

**Comment by jaksmid** [comment]
Same issue, the workaround with --force worked.

**Comment by henningpeters** [comment]
Meanwhile docs (https://spacy.io/) include ```--force``` flag, I think the issue can be closed?

**Comment by honnibal** [comment]
This should be fixed in the new release, thanks to the revised model download and install system Henning has written.
