### ISSUE TITLE
AssertionError when parsing empty string

### ISSUE THREAD

**Issue by leofidus** [honnibal/spaCy#19]
I happened to stumble over this while parsing a large dataset: spaCy throws an AssertionError when trying to parse an empty string.

Minimal Example:

```python
from spacy.en import English
nlp = English()
nlp(u"")
```

results in

```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    nlp(u"")
  File "/usr/local/lib/python2.7/dist-packages/spacy/en/__init__.py", line 149, in __call__
    self.parser(tokens)
  File "spacy/syntax/parser.pyx", line 77, in spacy.syntax.parser.GreedyParser.__call__ (spacy/syntax/parser.cpp:4122)
  File "spacy/syntax/_state.pyx", line 128, in spacy.syntax._state.init_state (spacy/syntax/_state.cpp:2715)
  File "spacy/syntax/_state.pyx", line 33, in spacy.syntax._state.push_stack (spacy/syntax/_state.cpp:1855)
AssertionError
```

**Comment by NSchrading** [comment]
I've also run into this problem. My machine is running Linux Mint 16, 64-bit. I feel like this should be a priority to fix since it prevents analyzing large datasets (e.g. data from the internet) that (presumably) contain weird formatting that result in empty string tokens.

**Comment by honnibal** [comment]
Thanks for the report, and sorry it took me a while to get to it. The fix should be published in master and on pip.

I'd intended this to be the behaviour for empty strings, but left a temporary assertion in the parser.
