### ISSUE TITLE
Import Build issue, OSX

### ISSUE THREAD

**Issue by jeregrine** [honnibal/spaCy#20]
Spacy installed fine with pip. Run the download command and...

```
➜  text-processing  python -m spacy.en.download
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 101, in _get_module_details
    loader = get_loader(mod_name)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "/usr/local/lib/python2.7/site-packages/spacy/en/__init__.py", line 6, in <module>
    from ..vocab import Vocab
  File ".env/lib/python2.7/site-packages/Cython/Includes/numpy/__init__.pxd", line 861, in init spacy.vocab (spacy/vocab.cpp:9066)
ValueError: numpy.ufunc has the wrong size, try recompiling

```

**Comment by jeregrine** [comment]
Upgrading numpy fixed it.Sorry
