### ISSUE TITLE
Error while installing using pip

### ISSUE THREAD

**Issue by christiaanw** [honnibal/spaCy#36]
I'm getting a failure to install using pip install spacy AND using pip to install the cloned git, with the following reports during install:

```python
Requirement already satisfied (use --upgrade to upgrade): cython in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Downloading/unpacking cymem>=1.11 (from -r requirements.txt (line 2))
  Downloading cymem-1.11.tar.gz
  Running setup.py (path:/tmp/pip_build_root/cymem/setup.py) egg_info for package cymem
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/cymem/setup.py", line 7, in <module>
        exts = cythonize([Extension("cymem.cymem", ["cymem/cymem.pyx"])])
      File "/usr/local/lib/python2.7/dist-packages/Cython/Distutils/extension.py", line 87, in __init__
        **kw)
    TypeError: unbound method __init__() must be called with Extension instance as first argument (got Extension instance instead)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/cymem/setup.py", line 7, in <module>

    exts = cythonize([Extension("cymem.cymem", ["cymem/cymem.pyx"])])

  File "/usr/local/lib/python2.7/dist-packages/Cython/Distutils/extension.py", line 87, in __init__

    **kw)

TypeError: unbound method __init__() must be called with Extension instance as first argument (got Extension instance instead)

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/cymem
```

**Comment by syllog1sm** [comment]
Try doing

    pip install --upgrade setuptools

**Comment by christiaanw** [comment]
Works! Wouldn't have figured that out myself, thanks!
